apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  labels:
    app: k8s-old-pod-killer
    release: {{ .Release.Name }}
    {{- with .Values.extraLabel }}
{{ toYaml . | indent 4 }}
    {{- end }}
